export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Best Surgeon in Malur,Whitefield,Kolar,Hoskote | Dr. Shubhodaya R Surgeon</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Inside index.html -->
<meta property="og:title" content="Best Surgeon in Malur,Whitefield,Kolar,Hoskote | Dr. Shubhodaya R Surgeon">
<meta property="og:description" content="Need a top surgeon in Malur? Dr. Shubhodaya R Surgeon offers expert surgical
care with 8+ years of experience. Book an appointment today.">
<meta property="og:type" content="website">
<!-- <meta property="og:url" content="https://drsmithclinic.com" />
<meta property="og:image" content="https://drsmithclinic.com/assets/og-image.jpg" />
<meta name="twitter:card" content="summary_large_image" /> -->

  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>@keyframes slideIn{0%{transform:translateY(30px);opacity:0}to{transform:translateY(0);opacity:1}}@keyframes fadeIn{0%{opacity:0}to{opacity:1}}.animate-slide-in{animation:slideIn .8s ease forwards}.animate-fade-in{animation:fadeIn 1.2s ease forwards}
</style><link rel="stylesheet" href="styles-F3VWX5UC.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-F3VWX5UC.css"></noscript><style ng-app-id="ng">.app-wrapper[_ngcontent-ng-c3814283702]{display:flex;flex-direction:column;min-height:100vh}.main-content[_ngcontent-ng-c3814283702]{flex:1;padding:2rem 1rem}</style><style ng-app-id="ng">.header[_ngcontent-ng-c913772625]{background:#fff;box-shadow:0 2px 10px #0000001a;padding:1rem 2rem;position:sticky;top:0;z-index:100}.header[_ngcontent-ng-c913772625]   .container[_ngcontent-ng-c913772625]{display:flex;justify-content:space-between;align-items:center}.header[_ngcontent-ng-c913772625]   nav[_ngcontent-ng-c913772625]   a[_ngcontent-ng-c913772625]{margin:0 1rem;text-decoration:none;color:#0077b6;font-weight:500;transition:color .3s}.header[_ngcontent-ng-c913772625]   nav[_ngcontent-ng-c913772625]   a[_ngcontent-ng-c913772625]:hover{color:#023e8a}.animate-slide-in[_ngcontent-ng-c913772625]{animation:_ngcontent-ng-c913772625_slideIn .7s ease-in-out forwards}@keyframes _ngcontent-ng-c913772625_slideIn{0%{transform:translateY(-20px);opacity:0}to{transform:translateY(0);opacity:1}}h1[_ngcontent-ng-c913772625]{color:#023e8a}</style><style ng-app-id="ng">.footer[_ngcontent-ng-c644545856]{background:#023e8a;color:#fff;text-align:center;padding:1.5rem;margin-top:3rem}.animate-fade-in[_ngcontent-ng-c644545856]{animation:_ngcontent-ng-c644545856_fadeIn 1.2s ease-in}@keyframes _ngcontent-ng-c644545856_fadeIn{0%{opacity:0}to{opacity:1}}</style><meta name="description" content="Need a top surgeon in Malur? Dr. Shubhodaya R Surgeon offers expert surgical
     care with 8+ years of experience. Book an appointment today."><meta name="robots" content="index, follow"><style ng-app-id="ng">.about[_ngcontent-ng-c2591198944]{padding:2.5rem}.about[_ngcontent-ng-c2591198944]   h2[_ngcontent-ng-c2591198944]{color:#023e8a}.about[_ngcontent-ng-c2591198944]   p[_ngcontent-ng-c2591198944]{font-size:1.05rem;margin:.75rem 0;line-height:1.6}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.6" _nghost-ng-c3814283702 ngh="1" ng-server-context="ssg"><div _ngcontent-ng-c3814283702 class="app-wrapper"><app-header _ngcontent-ng-c3814283702 _nghost-ng-c913772625 ngh="0"><header _ngcontent-ng-c913772625 class="header animate-slide-in"><div _ngcontent-ng-c913772625 class="container"><h1 _ngcontent-ng-c913772625>Dr. Shubhodaya R</h1><nav _ngcontent-ng-c913772625><a _ngcontent-ng-c913772625 routerlink="/" href="/" jsaction="click:;">Home</a><a _ngcontent-ng-c913772625 routerlink="about" href="/about" jsaction="click:;">About</a><a _ngcontent-ng-c913772625 routerlink="services" href="/services" jsaction="click:;">Services</a><a _ngcontent-ng-c913772625 routerlink="contact" href="/contact" jsaction="click:;">Contact</a></nav></div></header></app-header><main _ngcontent-ng-c3814283702 class="main-content"><router-outlet _ngcontent-ng-c3814283702></router-outlet><app-about _nghost-ng-c2591198944 ngh="0"><section _ngcontent-ng-c2591198944 class="about animate-slide-in"><h2 _ngcontent-ng-c2591198944>Meet Dr.Shubhodaya R</h2><p _ngcontent-ng-c2591198944> Dr. Shubhodaya R has over 8 years of experience in general, and laparoscopic surgery, specializing in laparoscopic [Hernia, Gallbladder, Appendix] and laser [Varicose Veins, Hemorrhoids, Fistula] and Thyroid procedures.</p><p _ngcontent-ng-c2591198944>He is a board-certified surgeon committed to providing compassionate, personalized care for every patient.</p></section></app-about><!----></main><app-footer _ngcontent-ng-c3814283702 _nghost-ng-c644545856 ngh="0"><footer _ngcontent-ng-c644545856 class="footer animate-fade-in"><div _ngcontent-ng-c644545856 class="container"><p _ngcontent-ng-c644545856>© 2025 Dr. Shubhodaya R | All Rights Reserved</p><p _ngcontent-ng-c644545856>Adarsha Nagar, Malur</p></div></footer></app-footer></div></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-36ZTN2NW.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"3":[{"i":"c2591198944","r":1}]}}]}</script></body></html>`;